### ISSUE TITLE
upload 大文件报错

### ISSUE THREAD

**Issue by story-x** [guicaiyue/plugin-githuboss#1]
![image](https://user-images.githubusercontent.com/45375162/234837323-c06ecca8-e82a-45f7-ac42-92217b2611c0.png)

需要开代理吗？

**Comment by guicaiyue** [comment]
我没有开代理也可以
我看日志的第一行文件路径有null字符，是不是配置有不理解的地方。
我这边也没有对github上传做图片大小限制，如果可以，请提供下图片我这边试一下。

**Comment by story-x** [comment]
> 我没有开启代理也可以让 我看日志的第一行文件路边有null字符符，是不是配置了无法理解的地方。 我这边也没有对github上传图片大小型限制，如如果可以，请提供下图片我这个边试一下。

这个是报错的图片和log
[https://wwsd.lanzoue.com/iuh9u0u59wqd](https://wwsd.lanzoue.com/iuh9u0u59wqd)

**Comment by guicaiyue** [comment]
我已经复现并解决这个问题，你升级下1.0.1版本再尝试下。
这是我的成功截图，上传速度很慢
![成功上传](https://user-images.githubusercontent.com/43875377/235279934-caedce51-575e-49da-bb40-d27dc08657a8.gif)


> > 我没有开启代理也可以让 我看日志的第一行文件路边有null字符符，是不是配置了无法理解的地方。 我这边也没有对github上传图片大小型限制，如如果可以，请提供下图片我这个边试一下。
> 
> 这个是报错的图片和log https://wwsd.lanzoue.com/iuh9u0u59wqd

我已经复现并解决这个问题，你升级下1.0.1版本再尝试下。
这是我的成功截图，上传速度很慢
![成功上传](https://user-images.githubusercontent.com/43875377/235279934-caedce51-575e-49da-bb40-d27dc08657a8.gif)

**Comment by guicaiyue** [comment]
@story-x 
我已经复现并解决这个问题，你升级下1.0.1版本再尝试下。
这是我的成功截图，上传速度很慢
![成功上传](https://user-images.githubusercontent.com/43875377/235279934-caedce51-575e-49da-bb40-d27dc08657a8.gif)

**Comment by erruicoders** [comment]
[https://gitee.com/ruirui0520/images/raw/master/168278630234220230430003134.png](url)
我应该也是遇到了这个问题，但是不知道是不是我配置的问题

**Comment by erruicoders** [comment]
![error](https://gitee.com/ruirui0520/images/raw/master/168278630234220230430003134.png)
我应该也是遇到了这个问题，但是不知道是不是我配置的问题

**Comment by guicaiyue** [comment]
@erruicoders 你这个不是大小问题，我猜测可能是存储配置的信息配错了，或者是token错了，导致调用GIthub API返回了一个我意料以外的结果，导致转JSON报错

**Comment by erruicoders** [comment]
那我把我有疑问的都问一下吧
![](https://fastly.jsdelivr.net/gh/erruicoders/utools-filebed@main/16828430031501682843002986.png)
基本信息的邮箱账号和用户账号就是GitHub的邮箱账号和用户名吧
![](https://fastly.jsdelivr.net/gh/erruicoders/utools-filebed@main/16828430681371682843067838.png)
存储配置的名称就是随便填的吧，账号名是halo当前的账号名还是github的账号名，当前账号就是halo的账号吧
ps:这两个我刚反着填了也不行
![](https://fastly.jsdelivr.net/gh/erruicoders/utools-filebed@main/16828435501411682843549937.png)
这是我github的配置
![](https://fastly.jsdelivr.net/gh/erruicoders/utools-filebed@main/16828438391391682843838990.png)
![](https://fastly.jsdelivr.net/gh/erruicoders/utools-filebed@main/16828439681461682843967626.png)
报错信息+日志

**Comment by erruicoders** [comment]
@guicaiyue 话说你14个小时前回复的我，半夜三点，emmmm

**Comment by guicaiyue** [comment]
@erruicoders 不好意思，五一出去玩了，你这个问题我确实不知道怎么解决，但我认为你的配置步骤是正确的。
所以我更新了1.0.1的包，增加了一些日志输出。
希望能帮助我们分析问题。
第一步：你需要重新升级1.0.1这个包
第二步：停止 halo
第三步：在 Java 启动命令上增加一行 logging.level.run.halo.oss=DEBUG 命令
第四步：再次启动 halo。
例子：比如使用 Docker Compose 部署的
第一步：执行命令停止运行中的容器组 cd ~/halo && docker-compose down
第二步：修改 docker-compose.yaml 配置中 halo 的command 增加一行：- --logging.level.run.halo.oss=DEBUG
第三步：docker-compose up -d 启动容器组

第二步截图如下
![image](https://user-images.githubusercontent.com/43875377/236118433-2d8e3975-4a7d-462e-b44e-90eb2081fabc.png)
